// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;
using TrainTracker.Models;

namespace TrainTracker.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("TrainTracker.Models.TrainStation", b =>
                {
                    b.Property<int>("TrainStationId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Blue");

                    b.Property<bool>("Brown");

                    b.Property<string>("DescStationName");

                    b.Property<string>("Direction");

                    b.Property<bool>("Green");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<string>("MapId");

                    b.Property<bool>("Orange");

                    b.Property<bool>("Pink");

                    b.Property<bool>("Purple");

                    b.Property<bool>("PurpleExpress");

                    b.Property<bool>("Red");

                    b.Property<string>("StationName");

                    b.Property<string>("StopId");

                    b.Property<string>("StopName");

                    b.Property<bool>("Yellow");

                    b.Property<bool>("ada");

                    b.HasKey("TrainStationId");

                    b.ToTable("TrainStations");
                });
#pragma warning restore 612, 618
        }
    }
}
